apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP
  sessionAffinity: ClientIP  # Define a afinidade de sessão com base no IP do cliente
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # Define o tempo de expiração da afinidade da sessão (opcional)